const members = [
  {
    "first name": "John",
    "last name": "Doe",
    "job title": "Software Engineer",
    department: "Engineering",
    manager: null,
    location: "Glasgow",
    "first aider": "No",
    "user slack": "johndoe",
    timezone: "America/Los_Angeles",
  },
  {
    "first name": "Jane",
    "last name": "Doe",
    "job title": "Software Engineer",
    department: "Engineering",
    manager: "John Doe",
    location: "Leeds",
    "first aider": "No",
    "user slack": "janedoe",
    timezone: "America/Los_Angeles",
  },
  {
    "first name": "Bob",
    "last name": "Doe",
    "job title": "Software Engineer",
    department: "Engineering",
    manager: "Jane Doe",
    location: "Cape Town",
    "first aider": "No",
    "user slack": "bobdoe",
    timezone: "America/Los_Angeles",
  },
  {
    "first name": "Sally",
    "last name": "Doe",
    "job title": "Software Engineer",
    department: "Engineering",
    manager: "Jane Doe",
    location: "Rome",
    "first aider": "No",
    "user slack": "sallydoe",
    timezone: "America/Los_Angeles",
  },
];
module.exports = members;
